#服务器相关
server:
  port: 8080

#spring配置相关
spring:
  mvc:
    #视图解析器
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #数据源 druid是alibaba的数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/two?useUnicode=true&characterEncoding=utf-8&serverTimezone
      username: root
      password: 123456

#配置日志记录工具
logging:
  level:
    org:
      #日志信息的打印
      springframework: error
    com:
      example:
        huan:
          mapper: debug

#配置mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml